### ISSUE TITLE
关于使用说明

### ISSUE THREAD

**Issue by Penghaiku** [zpxrainbowdash/tencent-meeting-checkin#1]
## 请问如何配合PC端腾讯会议软件使用点名签到呢？

**Comment by FeiZhaixiage** [comment]
pc端的腾讯会议软件会有聊天框 只要让成员把真实姓名发送到聊天框内直到等待结束（让成员在有时间限制的情况下进行发送）时间到了后 全选聊天框内所有文本 输入到输入框内即可（第一次使用它会自动创建签到表.xls 请在这里把要进行签到的名单依次输入并保存（不得删除表1.1中的字符“姓名”需要删除表1.2中的空格））

运行程序即可查看签到情况（亦可选择唠叨模式或简洁模式）如想输出表格记录每天的签到信息点击输出表格即可 （它会输出至签到表.xls）

以上操作基于优雅签到4.1

由于现在5.0及其不稳定 不推荐使用

视频介绍：https://www.bilibili.com/video/av97096093/
